name: Lint & Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Oculus OpenXR SDK
        uses: actions/checkout@v2
        with:
          repository: zigen-project/oculus-openxr-mobile-sdk
          path: ovr_openxr_mobile_sdk
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
          submodules: recursive

      - name: ClangFormat Check
        run: find . -regex "^\.\/app/src/main/cpp/.*\.\(h\|cpp\)" | xargs clang-format-14 --dry-run -Werror
        working-directory: ./main

      - name: Gradle build
        run: |
          echo "ovr_openxr_mobile_sdk.dir=$GITHUB_WORKSPACE/ovr_openxr_mobile_sdk" > local.properties
          ./gradlew build
        working-directory: ./main

      - name: Upload results Artifact
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: results
          path: |
            **/build/reports/lint-results-*.html
            **/build/reports/lint-results-*.xml
          if-no-files-found: error
          retention-days: 14
